server:
  # 访问端口
  port:
  servlet:
    # 访问路径
    context-path: /

  ssl:
    key-store:
    key-store-password:
    key-store-type:



# SpringMVC静态资源路径
debug: false #开启日志
spring:

  # 指定服务名
  application:
    name:

  freemarker:
    cache: false

  # 指定时区
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  mvc:
    # 指定静态文件路径
    static-path-pattern: /static/**

  # 数据库
  datasource:
    # MariaDB数据库
    #    driver-class-name: org.mariadb.jdbc.Driver
    # MySQL数据库
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://domain:port/user_database?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: username
    password: password
    type: com.zaxxer.hikari.HikariDataSource

    # Hikari连接池
    hikari:
      maximum-pool-size: 8
      minimum-idle: 4
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 45000
      auto-commit: true
      pool-name: HikariCP




  # redis
  redis:
    host: domain
    port: port
    connect-timeout: 20000
    password: pwd
    jedis:
      pool:
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0




# Mybatis-Plus
mybatis-plus:
  mapper-locations:
    - classpath*:mapper/*.xml
  typeAliasesPackage: com.linhei.queryuserid.entity
  global-config:
    db-config:
      id-type: ASSIGN_ID
    enable-sql-runner: true


